#
# A Test Workflow for Building OpenWrt
#

name: Build LEDE AMD64 

# Add a button to trigger the workflow manually
on: 
 workflow_dispatch:
 
# A series of steps
jobs:
 Build_LEDE:
  runs-on: ubuntu-latest
  
  steps:
   - name: Checkout
     uses: actions/checkout@main
     
   - name: looklook
     run: |
      sudo apt-get update -y
      sudo apt-get full-upgrade -y
      sudo apt-get install neofetch -y
      
   - name: 输出当前路径的内容
     run: ls
   
